-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 15:53:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Enrolled Students
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Enrolled Students
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Enrolled Students` DEFAULT CHARACTER SET utf8 ;
USE `Enrolled Students` ;

-- -----------------------------------------------------
-- Table `Enrolled Students`.`Student_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enrolled Students`.`Student_Info` (
  `Student_ID` INT UNSIGNED NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enrolled Students`.`Program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enrolled Students`.`Program` (
  `Student_ID` INT UNSIGNED NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `Classes` VARCHAR(45) NOT NULL,
  `Advisor` VARCHAR(45) NOT NULL,
  `Program_Student_ID` INT UNSIGNED NOT NULL,
  `Program_Major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_ID`, `Major`, `Program_Student_ID`, `Program_Major`),
  INDEX `fk_Program_Program_idx` (`Program_Student_ID` ASC, `Program_Major` ASC) VISIBLE,
  CONSTRAINT `fk_Program_Program`
    FOREIGN KEY (`Program_Student_ID` , `Program_Major`)
    REFERENCES `Enrolled Students`.`Program` (`Student_ID` , `Major`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
